# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  name: Default

steps:
- script: 
    echo "JAVA_HOME_11_X64 is $JAVA_HOME_11_X64"
    export JAVA_HOME=$JAVA_HOME_11_X64
    export PATH=$JAVA_HOME/bin:$PATH
    java -version
    mvn -v
    mvn clean install
  displayName: 'Check Java & Maven and Build'  

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '11.0.26'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
